const openWeatherApiKey = 'dbbfd2a8203a8f1f0a2fb761955a35a4';
const popularCities = [
  'New York',
  'London',
  'Paris',
  'Tokyo',
  'Chicago',
  'Berlin',
  'Dubai',
  'Rome',
  'Barcelona',
  'Madrid',
  'Toronto',
  'Las Vegas',
  'Miami',
  'Boston',
  'Sydney',
  'Singapore',
  'Hong Kong',
  'Bangkok',
];
