// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDazUOaPbckMR243eBUhvT39pp1QTzLGrc',
    appId: '1:28296000178:web:185a64934a81b8a2264fab',
    messagingSenderId: '28296000178',
    projectId: 'weather-auth-app',
    authDomain: 'weather-auth-app.firebaseapp.com',
    storageBucket: 'weather-auth-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5FKy-k75868GknJruf6Wo0xEFJ7wjBnM',
    appId: '1:28296000178:android:1999a0a036fffff9264fab',
    messagingSenderId: '28296000178',
    projectId: 'weather-auth-app',
    storageBucket: 'weather-auth-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrOOnrEdKdipEnidxwkVVlVtboe-Upsa0',
    appId: '1:28296000178:ios:4ed5b2552ba049d9264fab',
    messagingSenderId: '28296000178',
    projectId: 'weather-auth-app',
    storageBucket: 'weather-auth-app.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrOOnrEdKdipEnidxwkVVlVtboe-Upsa0',
    appId: '1:28296000178:ios:4ed5b2552ba049d9264fab',
    messagingSenderId: '28296000178',
    projectId: 'weather-auth-app',
    storageBucket: 'weather-auth-app.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDazUOaPbckMR243eBUhvT39pp1QTzLGrc',
    appId: '1:28296000178:web:b031508143e3f2ac264fab',
    messagingSenderId: '28296000178',
    projectId: 'weather-auth-app',
    authDomain: 'weather-auth-app.firebaseapp.com',
    storageBucket: 'weather-auth-app.appspot.com',
  );
}
